variables:
  GIT_STRATEGY: none

before_script:
  - git config --global user.email "vitalykay@gmail.com"
  - git config --global user.name "vitalykay"

deploy: 
  stage: deploy
  script: 
    - git clone git@gitlab:testproj/beonepage.git
    - scp -r ~/beonepage wordpress:~/beonepage
    - ssh wordpress sudo mv ~/beonepage /var/www/html/www.vitalykay-netology-diplom.tk/wp_content
  only:
    - master
    - tags
