variables:
  GIT_STRATEGY: none

before_script:
  - git config --global user.email "vitalykay@gmail.com"
  - git config --global user.name "vitalykay"
  - rm -r -f ~/beonepage

deploy: 
  stage: deploy
  script: 
    - git clone git@gitlab:testproj/beonepage.git ~/beonepage
    - scp -r ~/beonepage wordpress:~/beonepage
    - ssh wordpress sudo mv -f ~/beonepage/ /var/www/html/www.vitalykay-netology-diplom.tk/wp-content
  only:
    - master
    - tags
